Document: v4lsink
Title: Debian v4lsink Manual
Author: <insert document author here>
Abstract: This manual describes what v4lsink is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/v4lsink/v4lsink.sgml.gz

Format: postscript
Files: /usr/share/doc/v4lsink/v4lsink.ps.gz

Format: text
Files: /usr/share/doc/v4lsink/v4lsink.text.gz

Format: HTML
Index: /usr/share/doc/v4lsink/html/index.html
Files: /usr/share/doc/v4lsink/html/*.html
